http:
  port: 4040
  host: 'localhost'

postgreaSQL:
  user: 'postgres'
  host: 'localhost'           
  database: 'FeedbackDB'   
  password: '12345678' 
  port: 5432
  filters: 
    status: ['Обсуждается','активен','Не активен']
    category: ['Другое','Баг','UI','Функциональность','Дороботка']

redis:
  host: '127.0.0.1'
  port: 6379

resetPass:
  email: 'feedback-2025@mail.ru'
  password: '2ttLuV2MRHYyGZkuXk88'
  
jwt: 'privat' 
